### ISSUE TITLE
Suggestion: Modern and convent library for configs

### ISSUE THREAD

**Issue by NightMirror21** [Shershnyaga007/BetterCallFishing#9]
What do you think of the java-serializer library from the Elytrium team? It makes writing configs much easier for me, as well as supports convenient commenting in them. I actively use it in my project. Link: https://github.com/Elytrium/java-serializer

**Comment by Shershnyaga007** [comment]
Hi! In my other projects (not only minecraft) I use [SpongePowered/Configurate](https://github.com/SpongePowered/Configurate), because I'm already used to it and it's quite functional 😉)
In the process I was developing a small wrapper for ease of use in my projects, but I don’t have time for create it.
However, java-serializer seems more convenient and lightweight. Thank you!
